spring.application.name=api-ai
#spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.5